name: Publish Flowbite-Svelte Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10.10.0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: https://npm.pkg.github.com/
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Build
        run: pnpm build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          FATHOM_ID: "ABCDEFGF"
      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
